# -*- coding: utf-8 -*-
"""GITHUBPY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GqvI8tX_l9E6F9ItMo1om2ZN6cttflzn
"""

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

print("\n--- Arithmetic Operators ---")
print("Addition =", a + b)
print("Subtraction =", a - b)
print("Multiplication =", a * b)
print("Division =", a / b)
print("Floor Division =", a // b)
print("Modulus =", a % b)
print("Exponent =", a ** b)

print("\n--- Relational Operators ---")
print("a == b :", a == b)
print("a != b :", a != b)
print("a > b  :", a > b)
print("a < b  :", a < b)
print("a >= b :", a >= b)
print("a <= b :", a <= b)


ch = input("\nEnter a single character: ")

print("\n--- Character Type Check ---")
if len(ch) != 1:
    print("Please enter only one character.")
elif ch.isalpha():
    if ch.isupper():
        print("The character is an Uppercase Alphabet.")
    else:
        print("The character is a Lowercase Alphabet.")
elif ch.isdigit():
    print("The character is a Digit.")
else:
    print("The character is a Special Character.")