# -*- coding: utf-8 -*-
"""leet16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bAi5MIOEbhiUnys7307M3RdpJcbAEtGg
"""

class Solution:
    def threeSumClosest(self, nums, target):
        nums.sort()
        closest = nums[0] + nums[1] + nums[2]

        for i in range(len(nums) - 2):
            left = i + 1
            right = len(nums) - 1

            while left < right:
                total = nums[i] + nums[left] + nums[right]

                if abs(target - total) < abs(target - closest):
                    closest = total

                if total < target:
                    left += 1
                elif total > target:
                    right -= 1
                else:
                    return total

        return closest