# -*- coding: utf-8 -*-
"""leet66.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bAi5MIOEbhiUnys7307M3RdpJcbAEtGg
"""

class Solution:
    def plusOne(self, digits):
        n = len(digits)

        for i in range(n - 1, -1, -1):
            if digits[i] < 9:
                digits[i] += 1
                return digits
            digits[i] = 0

        return [1] + digits