# -*- coding: utf-8 -*-
"""leet34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bAi5MIOEbhiUnys7307M3RdpJcbAEtGg
"""

class Solution:
    def searchRange(self, nums, target):
        def findFirst():
            left, right = 0, len(nums) - 1
            ans = -1

            while left <= right:
                mid = (left + right) // 2

                if nums[mid] == target:
                    ans = mid
                    right = mid - 1
                elif nums[mid] < target:
                    left = mid + 1
                else:
                    right = mid - 1

            return ans

        def findLast():
            left, right = 0, len(nums) - 1
            ans = -1

            while left <= right:
                mid = (left + right) // 2

                if nums[mid] == target:
                    ans = mid
                    left = mid + 1
                elif nums[mid] < target:
                    left = mid + 1
                else:
                    right = mid - 1

            return ans

        return [findFirst(), findLast()]